			package form.tuyendung;
			
			public class demo1 {
			public String out ="<div class=\"row\">"
								+ "<div class=\"hidden-xs col-sm-2\">"
								+ "<a target=\"_blank\" href=\"https://www.topcv.vn/viec-lam/net-developer/1778.html?ref=ctbqt\" class=\"company-logo\">"
								+"<img src=\"images/cty.jpg\" style=\"width: 150px; height: 150px; margin: 10px;\" alt=\"Global CyberSoft\" title=\".NET Developer\">"
								+"</a>"
								+"</div>"
								+"<div class=\"col-md-10 col-sm-10\" style=\"padding-left: 60px;\">"
								+"<h4 class=\"job-title\">"
								+"<a target=\"_blank\" class=\"text-highlight \" href=\"https://www.topcv.vn/viec-lam/net-developer/1778.html?ref=ctbqt\">"
								+"<span class=\"bold\">"
								+"<bean:write name=\"baiviet\" property=\"maBaiViet\"/>"
								+"<bean:write name=\"baiviet\" property=\"tieuDe\" filter=\"false\"/>"
								+"</span>"
								+"</a>"
								+"</h4>"
								+"</p>"
								+"<p class=\"job-salary\">"
								+"	<span><i class=\"glyphicon glyphicon-home\"></i> <bean:write name=\"baiviet\" property=\"noiLamViec\"/></span>"
								+"	<span><i class=\"glyphicon glyphicon-bed\"></i> To&agrave;n thời gian</span>"
								+"	<span><i class=\"glyphicon glyphicon-usd\"></i> <bean:write name=\"baiviet\" property=\"luong\"/></span>"
								+"	<span><i class=\"glyphicon glyphicon-list-alt\"></i>  <bean:write name=\"baiviet\" property=\"hanNopHoSo\"/></span>"
								+"</p>"
								+" <bean:define id=\"maBaiViet\" name=\"baiviet\" property=\"maBaiViet\"></bean:define>"
								+"	<html:link action=\"/ct-baituyendung?maBaiViet=${maBaiViet}\" target=\"_BLANK\">"
								+"		<span class=\"glyphicon glyphicon-edit\">Xem chi tiết ...</span>"
								+"	</html:link>"
								+"</div>"
								+"</div>";
			
			String ketqua="<div class=\"col-md-10 col-sm-10\" style=\"padding-left: 60px;\">"
							+ "<h4 class=\"job-title\">"
							+ "<a target=\"_blank\" class=\"text-highlight\" href=\"https://www.topcv.vn/viec-lam/net-developer/1778.html?ref=ctbqt\">"
							+"<span class=\"bold\"><bean:write name=\"baiviet\" property=\"maBaiViet\"/>"
							+ "<bean:write name=\"baiviet\" property=\"tieuDe\" filter=\"false\"/"
							+ "</span>"
							+ "</a>"
							+ "</h4>"
							+"<p class=\"shortDes\">"
							+"Cong ty A"
							+"</p>"
							+ "<p class=\"job-salary\">"
							+ "<span><i class=\"glyphicon glyphicon-home\"></i> <bean:write name=\"baiviet\" property=\"noiLamViec\"/></span>"
							+ "<span><i class=\"glyphicon glyphicon-bed\"></i> To&agrave;n thời gian</span>"
							+ "<span><i class=\"glyphicon glyphicon-usd\"></i> <bean:write name=\"baiviet\" property=\"luong\"/></span>"
							+ "<span><i class=\"glyphicon glyphicon-list-alt\"></i>  <bean:write name=\"baiviet\" property=\"hanNopHoSo\"/></span>"
							+ "</p>"
							+ " <bean:define id=\"maBaiViet\" name=\"baiviet\" property=\"maBaiViet\"></bean:define>"
							+ "<html:link action=\"/ct-baituyendung?maBaiViet=${maBaiViet}\" target=\"_BLANK\">"
							+ "		<span class=\"glyphicon glyphicon-edit\">Xem chi tiết ...</span>"
							+ "	</html:link>"
							+ "</div>";}
